version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  # Drupal 8 container
  drupal:
    image: druidfi/docker-drupal:php71-basic
    container_name: "${COMPOSE_PROJECT_NAME}-drupal"
    hostname: &hostname ${DRUPAL_URL}
    environment:
      VIRTUAL_HOST: *hostname
      WEBROOT: web
      # Site URI for Drush 9
      DRUSH_OPTIONS_URI: *hostname
    volumes:
      - ./drupal:/var/www/drupal/public_html:delegated
      - ssh:/tmp/amazeeio_ssh-agent:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:${DRUPAL_URL}"
    networks:
      - dev-network

networks:

  # Network from druidfi/stonehenge
  dev-network:
    name: stonehenge-network
    external: true

volumes:

  # Volume from druidfi/stonehenge
  ssh:
    name: stonehenge-ssh
    external: true
